version: '3.0'
services:
  event-processor:
    container_name: event-processor
    build: .
    environment:
      - RABBITMQ_URL=0.0.0.0:5672
      - REDIS_URL=0.0.0.0:6379
    network_mode: host
    ports:
      - 1323:1323
    depends_on:
      - rabbitmq
      - redis
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8
    network_mode: host
    command:
      - rabbitmq-server
    ports:
      - 5672:5672
      - 15692:15692
  redis:
    container_name: redis
    image: redis:6.0
    network_mode: host
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      - redis-server
    ports:
      - 6379:6379