version: '3.0'
services:
  event-processor:
    container_name: event-processor
    build: .
    restart: unless-stopped
    environment:
      - RABBITMQ_CONN=amqp://guest:guest@localhost:5672/
      - REDIS_HOST=0.0.0.0
      - REDIS_PORT=6379
      - MONGO_HOST=mongodb://localhost:27017/
      - MONGO_USER=mongo
      - MONGO_PASS=password1234
    network_mode: host
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq
      - mongo
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management
    network_mode: host
    command:
      - rabbitmq-server
    ports:
      - 5672:5672
      - 15672:15672
  mongo:
    container_name: mongo
    image: mongo:latest
    network_mode: host
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password1234
    ports:
      - 27017:27017